db:
  host: 'localhost'
  username: 'vinlt'
  password: 'TjmWjm824594'
  synchronize: true

server:
  origin: http://vui-nestjs-task-management-frontend.s3-website.us-east-2.amazonaws.com

jwt:
  secret: 'nltruongvi1999'